name: Hello

on: 
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: say hello
        run: echo "hello Github Action"
  
  date:
    runs-on: ubuntu-latest
    steps:
      - name: current time & Date
        run: echo "current time and date is $(date)"
  
  list_file_repo:
     runs-on: ubuntu-latest
     steps:
       - name: list files in repo
         run : ls -R ${{ github.workspace }}




  