name: Hello

on: 
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: say hello
        run: echo "hello Github Action"
  
  date:
    runs-on: ubuntu-latest
    steps:
      - name: current time & Date
        run: echo "current time and date is $(date)"
  
  list_file_repo:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v4

       - name: list files in repo
         run : ls -la
  
  Branch_name:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        run: echo "Branch name is ${{ github.ref_name }}"
 
  Runnner-Operating-system: 
    runs-on: ubuntu-latest
    steps: 
      - name: Print runner operating system
        run: echo "Runner OS is $RUNNER_OS"
  
  fail-coomand:
    runs-on: ubuntu-latest
    steps: 
      - name: Break It On Purpose
        run: docke --version



  